# Collections Endpoints

### get all collections
GET http://localhost:3000/collections

### get a specific collection by ID
GET http://localhost:3000/collections/68df3ddab4ad52ce056ad464

### create a new collection
POST http://localhost:3000/collections HTTP/1.1
Content-Type: application/json

{
  "title": "Midnight Bloom",
  "season": "Fall",
  "year": 2025,
  "designer": "Rodarte",
  "theme": "Gothic botanical",
  "description": "A moody collection exploring nocturnal flora using velvet textures and metallic accents.",
  "launchDate": "2025-10-02",
  "numberOfPieces": 10,
  "status": "active"
}

### update an existing collection by ID
PUT http://localhost:3000/collections/68df3ddab4ad52ce056ad464 HTTP/1.1
Content-Type: application/json

{
  "title": "Midnight Bloom Updated",
  "season": "Fall",
  "year": 2025,
  "designer": "Alexander McQueen",
  "theme": "Gothic botanical with a modern twist",
  "description": "An updated moody collection exploring nocturnal flora using velvet textures and metallic accents.",
  "launchDate": "2025-10-15",
  "status": "upcoming"
}

### delete a collection by ID
DELETE http://localhost:3000/collections/68df3ddab4ad52ce056ad464



# Brands Endpoints

### get all brands
GET http://localhost:3000/brands

### get a specific brand by ID
GET http://localhost:3000/brands/68e44b26dfec2396385db683

### create a new brand
POST http://localhost:3000/brands HTTP/1.1
Content-Type: application/json

{
  "name": "Louis Vuitton",
  "founder": "Louis Vuitton",
  "foundedYear": 1854,
  "headquarters": "Paris, France",
  "specialization": "Luxury fashion, leather goods, accessories",
  "currentCreativeDirector": "Pharrell Williams",
  "website": "https://www.louisvuitton.com",
  "notableCollections": ["LV Monogram", "Urban Edge"],
  "slogan": "L’Art du Voyage",
  "status": "active"
}

### update an existing brand by ID
PUT http://localhost:3000/brands/68e44b26dfec2396385db683 HTTP/1.1
Content-Type: application/json

{
  "name": "Louis Vuitton Updated",
  "founder": "Louis Vuitton",
  "foundedYear": 1854,
  "headquarters": "Paris, France",
  "specialization": "Luxury fashion, leather goods, accessories",
  "currentCreativeDirector": "Pharrell Williams",
  "website": "https://www.louisvuitton.com",
  "notableCollections": ["LV Monogram", "Urban Edge"],
  "slogan": "L’Art du Voyage",
  "status": "active"
}

### delete a brand by ID
DELETE http://localhost:3000/brands/68e44b93dfec2396385db68b
