### Designer get all designers
GET http://localhost:3000/designers



# Collections Endpoints

### get all collections
GET http://localhost:3000/collections

### get a specific collection by ID
GET http://localhost:3000/collections/68df3ddab4ad52ce056ad464

### create a new collection
POST http://localhost:3000/collections HTTP/1.1
Content-Type: application/json

{
  "title": "Midnight Bloom",
  "season": "Fall",
  "year": 2025,
  "designer": "Rodarte",
  "theme": "Gothic botanical",
  "description": "A moody collection exploring nocturnal flora using velvet textures and metallic accents.",
  "launchDate": "2025-10-02",
  "numberOfPieces": 10,
  "status": "active"
}

### update an existing collection by ID
PUT http://localhost:3000/collections/68df3ddab4ad52ce056ad464 HTTP/1.1
Content-Type: application/json

{
  "title": "Midnight Bloom Updated",
  "season": "Fall",
  "year": 2024,
  "designer": "Alexander McQueen",
  "theme": "Gothic botanical with a modern twist",
  "description": "An updated moody collection exploring nocturnal flora using velvet textures and metallic accents.",
  "launchDate": "2025-10-15",
  "status": "upcoming"
}

### delete a collection by ID
DELETE http://localhost:3000/collections/68df3ddab4ad52ce056ad464



# Brands Endpoints

### get all brands
GET http://localhost:3000/brands

### get a specific brand by ID
GET http://localhost:3000/brands/68e44b26dfec2396385db683

### create a new brand
POST http://localhost:3000/brands HTTP/1.1
Content-Type: application/json

{
  "name": "Louis Vuitton",
  "founder": "Louis Vuitton",
  "foundedYear": 1854,
  "headquarters": "Paris, France",
  "specialization": "Luxury fashion, leather goods, accessories",
  "currentCreativeDirector": "Pharrell Williams",
  "website": "https://www.louisvuitton.com",
  "notableCollections": ["LV Monogram", "Urban Edge"],
  "slogan": "L’Art du Voyage",
  "status": "active"
}

### update an existing brand by ID
PUT http://localhost:3000/brands/68e44b26dfec2396385db683 HTTP/1.1
Content-Type: application/json

{
  "name": "Louis Vuitton Updated",
  "founder": "Louis Vuitton",
  "foundedYear": 1854,
  "headquarters": "Paris, France",
  "specialization": "Luxury fashion, leather goods, accessories",
  "currentCreativeDirector": "Pharrell Williams",
  "website": "https://www.louisvuitton.com",
  "notableCollections": ["LV Monogram", "Urban Edge"],
  "slogan": "L’Art du Voyage",
  "status": "active"
}

### delete a brand by ID
DELETE http://localhost:3000/brands/68e44b93dfec2396385db68b


### Get all shows
GET http://localhost:3000/shows

### Post a new show
POST http://localhost:3000/shows HTTP/1.1
Content-Type: application/json

 {
  "collectionId": "68e1ae890a9ff25157e9e0ea",
  "location": "Paris Fashion Week",
  "date": "2024-03-15",
  "venue": "Louvre Museum",
  "specialGuests": ["Naomi Campbell", "Kendall Jenner"]
 }

### get a specific show by ID
GET http://localhost:3000/shows/68e9f26230d5e16cb7cc8994

### Update a specific show by ID
PUT http://localhost:3000/shows/68e9f26230d5e16cb7cc8994 HTTP/1.1
Content-Type: application/json

 {
  "collectionId": "68e1ae890a9ff25157e9e0ea",
  "location": "Milan Fashion Week",
  "date": "2024-04-10",
  "venue": "Duomo di Milano",
  "specialGuests": ["Gigi Hadid", "Bella Hadid"]
 }

### Delete a specific show by ID
DELETE http://localhost:3000/shows/68e9fb4446f46b533f601d20
